const EXAMPLE_ACTION_TYPES = {
  SET_EXAMPLES: "example/SET_EXAMPLES",
  SET_IS_EXAMPLES_HAS_MORE: "example/SET_IS_EXAMPLES_HAS_MORE",
  SET_FETCH_EXAMPLES_SEARCH: "example/SET_FETCH_EXAMPLES_SEARCH",
  SET_FETCH_EXAMPLES_PAGE: "example/SET_FETCH_EXAMPLES_PAGE",
  SET_FETCH_EXAMPLES_PER_PAGE: "example/SET_FETCH_EXAMPLES_PER_PAGE",
  SET_FETCH_EXAMPLES_INCLUDES: "example/SET_FETCH_EXAMPLES_INCLUDES",
  SET_FETCH_EXAMPLES_FILTER_COLUMN_A: "example/SET_FETCH_EXAMPLES_FILTER_COLUMN_A",
  SET_FETCH_EXAMPLES_FILTER_COLUMN_B: "example/SET_FETCH_EXAMPLES_FILTER_COLUMN_B",
  APPEND_EXAMPLES: "example/APPEND_EXAMPLES",
  FETCH_EXAMPLES_START: "example/FETCH_EXAMPLES_START",

  SET_EXAMPLE: "example/SET_EXAMPLE",
  SET_FETCH_EXAMPLES_LOADING: "example/SET_FETCH_EXAMPLES_LOADING",
  SET_FETCH_EXAMPLES_SUCCESS: "example/SET_FETCH_EXAMPLES_SUCCESS",
  SET_FETCH_EXAMPLES_FAILED: "example/SET_FETCH_EXAMPLES_FAILED",
  SET_FETCH_EXAMPLE_LOADING: "example/SET_FETCH_EXAMPLE_LOADING",
  SET_FETCH_EXAMPLE_SUCCESS: "example/SET_FETCH_EXAMPLE_SUCCESS",
  SET_FETCH_EXAMPLE_FAILED: "example/SET_FETCH_EXAMPLE_FAILED",
  FETCH_EXAMPLE_START: "example/FETCH_EXAMPLE_START",

  SET_CREATE_EXAMPLE_LOADING: "example/SET_CREATE_EXAMPLE_LOADING",
  SET_CREATE_EXAMPLE_SUCCESS: "example/SET_CREATE_EXAMPLE_SUCCESS",
  SET_CREATE_EXAMPLE_FAILED: "example/SET_CREATE_EXAMPLE_FAILED",
  CREATE_EXAMPLE_START: "example/CREATE_EXAMPLE_START",

  SET_UPDATE_EXAMPLE_LOADING: "example/SET_UPDATE_EXAMPLE_LOADING",
  SET_UPDATE_EXAMPLE_SUCCESS: "example/SET_UPDATE_EXAMPLE_SUCCESS",
  SET_UPDATE_EXAMPLE_FAILED: "example/SET_UPDATE_EXAMPLE_FAILED",
  UPDATE_EXAMPLE_START: "example/UPDATE_EXAMPLE_START",

  SET_DELETE_EXAMPLE_LOADING: "example/SET_DELETE_EXAMPLE_LOADING",
  SET_DELETE_EXAMPLE_SUCCESS: "example/SET_DELETE_EXAMPLE_SUCCESS",
  SET_DELETE_EXAMPLE_FAILED: "example/SET_DELETE_EXAMPLE_FAILED",
  DELETE_EXAMPLE_START: "example/DELETE_EXAMPLE_START",
};

export default EXAMPLE_ACTION_TYPES;
