const ORDER_ACTION_TYPES = {
  SET_ORDERS: "order/SET_ORDERS",
  SET_IS_ORDERS_HAS_MORE: "order/SET_IS_ORDERS_HAS_MORE",
  SET_FETCH_ORDERS_SEARCH: "order/SET_FETCH_ORDERS_SEARCH",
  SET_FETCH_ORDERS_PAGE: "order/SET_FETCH_ORDERS_PAGE",
  SET_FETCH_ORDERS_PER_PAGE: "order/SET_FETCH_ORDERS_PER_PAGE",
  APPEND_ORDERS: "order/APPEND_ORDERS",
  FETCH_ORDERS_START: "order/FETCH_ORDERS_START",

  SET_ORDER: "order/SET_ORDER",
  SET_FETCH_ORDERS_LOADING: "order/SET_FETCH_ORDER_LOADING",
  SET_FETCH_ORDERS_SUCCESS: "order/SET_FETCH_ORDER_SUCCESS",
  SET_FETCH_ORDERS_FAILED: "order/SET_FETCH_ORDER_FAILED",
  SET_FETCH_ORDER_LOADING: "order/SET_FETCH_ORDER_LOADING",
  SET_FETCH_ORDER_SUCCESS: "order/SET_FETCH_ORDER_SUCCESS",
  SET_FETCH_ORDER_FAILED: "order/SET_FETCH_ORDER_FAILED",
  FETCH_ORDER_START: "order/FETCH_ORDER_START",

  SET_CREATE_ORDER_LOADING: "order/SET_CREATE_ORDER_LOADING",
  SET_CREATE_ORDER_SUCCESS: "order/SET_CREATE_ORDER_SUCCESS",
  SET_CREATE_ORDER_FAILED: "order/SET_CREATE_ORDER_FAILED",
  CREATE_ORDER_START: "order/CREATE_ORDER_START",

  SET_UPDATE_ORDER_LOADING: "order/SET_UPDATE_ORDER_LOADING",
  SET_UPDATE_ORDER_SUCCESS: "order/SET_UPDATE_ORDER_SUCCESS",
  SET_UPDATE_ORDER_FAILED: "order/SET_UPDATE_ORDER_FAILED",
  UPDATE_ORDER_START: "order/UPDATE_ORDER_START",

  SET_DELETE_ORDER_LOADING: "order/SET_DELETE_ORDER_LOADING",
  SET_DELETE_ORDER_SUCCESS: "order/SET_DELETE_ORDER_SUCCESS",
  SET_DELETE_ORDER_FAILED: "order/SET_DELETE_ORDER_FAILED",
  DELETE_ORDER_START: "order/DELETE_ORDER_START",
};

export default ORDER_ACTION_TYPES;
