const PRODUCT_ACTION_TYPES = {
  SET_PRODUCTS: "product/SET_PRODUCTS",
  SET_IS_PRODUCTS_HAS_MORE: "product/SET_IS_PRODUCTS_HAS_MORE",
  SET_FETCH_PRODUCTS_SEARCH: "product/SET_FETCH_PRODUCTS_SEARCH",
  SET_FETCH_PRODUCTS_PAGE: "product/SET_FETCH_PRODUCTS_PAGE",
  SET_FETCH_PRODUCTS_PER_PAGE: "product/SET_FETCH_PRODUCTS_PER_PAGE",
  APPEND_PRODUCTS: "product/APPEND_PRODUCTS",
  FETCH_PRODUCTS_START: "product/FETCH_PRODUCTS_START",

  SET_PRODUCT: "product/SET_PRODUCT",
  SET_FETCH_PRODUCTS_LOADING: "product/SET_FETCH_PRODUCTS_LOADING",
  SET_FETCH_PRODUCTS_SUCCESS: "product/SET_FETCH_PRODUCTS_SUCCESS",
  SET_FETCH_PRODUCTS_FAILED: "product/SET_FETCH_PRODUCTS_FAILED",
  SET_FETCH_PRODUCT_LOADING: "product/SET_FETCH_PRODUCT_LOADING",
  SET_FETCH_PRODUCT_SUCCESS: "product/SET_FETCH_PRODUCT_SUCCESS",
  SET_FETCH_PRODUCT_FAILED: "product/SET_FETCH_PRODUCT_FAILED",
  FETCH_PRODUCT_START: "product/FETCH_PRODUCT_START",

  SET_CREATE_PRODUCT_LOADING: "product/SET_CREATE_PRODUCT_LOADING",
  SET_CREATE_PRODUCT_SUCCESS: "product/SET_CREATE_PRODUCT_SUCCESS",
  SET_CREATE_PRODUCT_FAILED: "product/SET_CREATE_PRODUCT_FAILED",
  CREATE_PRODUCT_START: "product/CREATE_PRODUCT_START",

  SET_UPDATE_PRODUCT_LOADING: "product/SET_UPDATE_PRODUCT_LOADING",
  SET_UPDATE_PRODUCT_SUCCESS: "product/SET_UPDATE_PRODUCT_SUCCESS",
  SET_UPDATE_PRODUCT_FAILED: "product/SET_UPDATE_PRODUCT_FAILED",
  UPDATE_PRODUCT_START: "product/UPDATE_PRODUCT_START",

  SET_DELETE_PRODUCT_LOADING: "product/SET_DELETE_PRODUCT_LOADING",
  SET_DELETE_PRODUCT_SUCCESS: "product/SET_DELETE_PRODUCT_SUCCESS",
  SET_DELETE_PRODUCT_FAILED: "product/SET_DELETE_PRODUCT_FAILED",
  DELETE_PRODUCT_START: "product/DELETE_PRODUCT_START",
};

export default PRODUCT_ACTION_TYPES;
